### PR TITLE
Add/fix `accessibilityLabel` property values for Clipboard, XAML and Lottie Example pages

### LINKED ISSUE #453: 'Name of a focuable element must not be null' error message from Accessibility Insights on Clipboard example page
Screenshot of Fastpass:

image

Looks like we need to have the accessibilityLabel prop defined on each of these.

### LINKED ISSUE #454: 'Name of a focuable element must not be null' error message from Accessibility Insights on Lottie example page
Screenshot of Fastpass: 

image

Looks like we need to have the accessibilityLabel prop defined on each of these.

### LINKED ISSUE #474: UIA Name and ControlType/LocalizedControlType property errors on Xaml example change.
Screenshot of Fastpass:

image

All errors are due to the UIA Name and UIA ControlType and LocalizedControlType properties having common text in their values. Will need to change the UIA Name properties (accessibilityLabel) for the impacted components.

### PR DESCRIPTION
**Pull request by Yajur-Grover**
## Description
Fix accessibilityLabel values to prevent issues with UIA ControlType/LocalizedControlType values being the same, or UIA Name property values being null on Lottie, Clipboard and XAML example pages.

### Why

Resolves #453 
Resolves #454 
Resolves #474 

### What

What changes were made to the codebase to solve the bug, add the functionality, etc. that you specified above.

## Screenshots
Clipboard before:
image

Clipboard After:
Clipboard After

Lottie Before:
image

Lottie After: 
Lottie After

XAML Before:
image

XAML After:
XAML After

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/react-native-gallery/pull/475)

### CODE REVIEW

File: __tests__/__snapshots__/App-test.js.snap [hunk 1]
```diff
@@ -54836,6 +54839,7 @@ exports[`Xaml Example Page 1`] = `
               }
             >
               <XamlControl
+                accessibilityLabel="Simple example"
```
Comment (marlenecota) [inline __tests__/__snapshots__/App-test.js.snap:54842]:
```suggestion
                accessibilityLabel="Simple button example"
```

File: __tests__/__snapshots__/App-test.js.snap [hunk 2]
```diff
@@ -56349,7 +56353,7 @@ You selected Option 1
               }
             >
               <XamlControl
-                accessibilityLabel="Simple example ComboBox"
+                accessibilityLabel="Simple example"
```
Comment (marlenecota) [inline __tests__/__snapshots__/App-test.js.snap:56356]:
```suggestion
                accessibilityLabel="Simple combobox example"
```

File: src/examples/LottieAnimationsExamplePage.tsx [hunk 3]
```diff
@@ -100,13 +100,22 @@ export const LottieAnimationsExamplePage: React.FunctionComponent<{}> = () => {
...
+          />
+          <Button
+            onPress={onResume}
+            title={'resume'}
+            accessibilityLabel="Resume"
+          />
+          <Button onPress={onReset} title="reset" accessibilityLabel="Reset" />
           <Button
             onPress={handlerChangeLoop}
             title={loop ? 'disable loop' : 'ative resume'}
```
Comment (marlenecota) [inline src/examples/LottieAnimationsExamplePage.tsx:117]: "ative"? is this a typo?

File: src/examples/LottieAnimationsExamplePage.tsx [hunk 4]
```diff
@@ -100,13 +100,22 @@ export const LottieAnimationsExamplePage: React.FunctionComponent<{}> = () => {
...
+            accessibilityLabel="Disable Loop"
```
Comment (marlenecota) [inline src/examples/LottieAnimationsExamplePage.tsx:118]: 'ative loop' can't be right, so I just put 'resume loop', but whatever it should be, it should match the title. 

```suggestion
            accessibilityLabel={loop ? 'disable loop' : 'resume loop'}
```

File: src/examples/XamlExamplePage.tsx [hunk 5]
```diff
@@ -113,7 +113,11 @@ const onRadioButtonSelected = (event) => {
         <TextBlock text="I am a XAML TextBlock." />
       </Example>
       <Example title="A simple XAML Button." code={example2jsx}>
-        <Button content={{string: 'XAML Button'}} onClick={() => {}} />
+        <Button
+          accessibilityLabel="Simple example"
```
Comment (marlenecota) [inline src/examples/XamlExamplePage.tsx:117]:
```suggestion
          accessibilityLabel="Simple button example"
```

File: src/examples/XamlExamplePage.tsx [hunk 6]
```diff
@@ -152,7 +156,7 @@ You selected Option ${selectedRadioButton}`}</Text>
         </View>
       </Example>
       <Example title="A simple ComboBox." code={example5jsx}>
-        <ComboBox accessibilityLabel="Simple example ComboBox" text="ComboBox">
+        <ComboBox accessibilityLabel="Simple example" text="ComboBox">
```
Comment (marlenecota) [inline src/examples/XamlExamplePage.tsx:159]:
```suggestion
        <ComboBox accessibilityLabel="Simple combobox example" text="ComboBox">
```

**Comment by Yajur-Grover** [comment]
@marlenecota for the accessibilityLabel changes, removing the component name for the label is intentional, since that is what is causing the issue within the UIA tree. Since the screen reader reads out the 'Name' property and 'ControlType' property consecutively, the 'Name' property cannot have the same value as the ControlType, since the screen reader will read out the same value twice. 

E.g if `accessibilityLabel='Simple combobox example'`, then `Name='Simple combobox example'` and `ControlType='Combobox'`, and the screenreader will say `'Simple combobox example, combobox'` which is a problem for understandability.

**Review by marlenecota — APPROVED** [review]

File: src/examples/LottieAnimationsExamplePage.tsx (hunk 3 above)
Comment (Yajur-Grover) [reply src/examples/LottieAnimationsExamplePage.tsx]: Most likely - applied the recommended change.

File: src/examples/ClipboardExamplePage.tsx [hunk 7]
```diff
@@ -43,16 +43,22 @@ export const ClipboardExamplePage: React.FunctionComponent<{}> = () => {
       <Example title="Copy text to the Clipboard." code={example1jsx}>
         <View style={{alignItems: 'flex-start', gap: 12}}>
           <Button
+            accessibilityLabel="Example copy text"
```
Comment (chrisglein) [inline src/examples/ClipboardExamplePage.tsx:46]: Why doesn't Button.title become the default accessibilityLabel?

File: src/examples/LottieAnimationsExamplePage.tsx [hunk 8]
```diff
@@ -100,13 +100,22 @@ export const LottieAnimationsExamplePage: React.FunctionComponent<{}> = () => {
...
-          <Button onPress={onReset} title="reset" />
+          <Button onPress={onPlay} title={'play'} accessibilityLabel="Play" />
+          <Button
+            onPress={onPause}
+            title={'pause'}
+            accessibilityLabel="Pause"
+          />
+          <Button
+            onPress={onResume}
+            title={'resume'}
```
Comment (chrisglein) [inline src/examples/LottieAnimationsExamplePage.tsx:111]:
```suggestion
            title="resume"
```

File: src/examples/LottieAnimationsExamplePage.tsx [hunk 9]
```diff
@@ -100,13 +100,22 @@ export const LottieAnimationsExamplePage: React.FunctionComponent<{}> = () => {
...
         />
         <View style={{flexDirection: 'row', gap: 12}}>
-          <Button onPress={onPlay} title={'play'} />
-          <Button onPress={onPause} title={'pause'} />
-          <Button onPress={onResume} title={'resume'} />
-          <Button onPress={onReset} title="reset" />
+          <Button onPress={onPlay} title={'play'} accessibilityLabel="Play" />
+          <Button
+            onPress={onPause}
+            title={'pause'}
```
Comment (chrisglein) [inline src/examples/LottieAnimationsExamplePage.tsx:106]:
```suggestion
            title="pause"
```

File: src/examples/LottieAnimationsExamplePage.tsx [hunk 10]
```diff
@@ -100,13 +100,22 @@ export const LottieAnimationsExamplePage: React.FunctionComponent<{}> = () => {
           }}
         />
         <View style={{flexDirection: 'row', gap: 12}}>
-          <Button onPress={onPlay} title={'play'} />
-          <Button onPress={onPause} title={'pause'} />
-          <Button onPress={onResume} title={'resume'} />
-          <Button onPress={onReset} title="reset" />
+          <Button onPress={onPlay} title={'play'} accessibilityLabel="Play" />
```
Comment (chrisglein) [inline src/examples/LottieAnimationsExamplePage.tsx:103]:
```suggestion
          <Button onPress={onPlay} title="play" accessibilityLabel="Play" />
```

File: src/examples/ClipboardExamplePage.tsx (hunk 7 above)
Comment (Yajur-Grover) [reply src/examples/ClipboardExamplePage.tsx:46]: I think it's because of how we define the accessibilityLabel property [here](https://github.com/microsoft/react-native-windows/blob/63d919e36e0d6ad93f1e772df53a1e7c1a5aa1da/vnext/src-win/Libraries/Components/Button.windows.js#L378). 

If we set the `accessibilityLabel` property based on the `title` instead would probably automatically do that. If the `title` property contains text that is the same as the ControlType (which would be 'button' here), then it's up to the client to add an appropriate `accessibilityLabel` property. Can open up a PR with this change if this approach makes sense.

Comment (chrisglein) [reply src/examples/ClipboardExamplePage.tsx:46]: It seems to match the cross-platform implementation:
https://github.com/facebook/react-native/blob/a6f5e5adebed3d9da411f99548e2d8ce96636e16/packages/react-native/Libraries/Components/Button.js#L366

It seems like a bad default to me personally... but we're matching core and that's what we should do. As in this is the same JS you'd use on mobile. It's just... duplicative and verbose. Oh well.

**Review by chrisglein — APPROVED** [review]
