### PR TITLE
Fix Screen Reader failing to announce “permissions is not available” text

### LINKED ISSUE #229: On Permissions page, Screen Reader fails to announce “permissions is not available” text.
Found during accessibility grading.

Tracking internal bug: https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/40128466

### PR DESCRIPTION
**Pull request by TatianaKapos**
## Description
Narrator reads out result from pressing permission button now by adding accessible property to View

### Why
Resolves  #229

### CODE REVIEW

File: src/examples/PermissionsExamplePage.tsx [hunk 1]
```diff
@@ -129,7 +129,7 @@ export const PermissionsExamplePage: React.FunctionComponent<{}> = () => {
         <Text style={{fontWeight: 'bold', paddingLeft: 10, color: colors.text}}>
           {perm}
         </Text>
-        <View focusable={getResultString(status) ? true : false}>
+        <View focusable={getResultString(status) ? true : false} accessible={getResultString(status) ? true : false}>
```
Comment (AgneLukoseviciute) [inline src/examples/PermissionsExamplePage.tsx:132]:
```suggestion
        <View focusable={getResultString(status)} accessible={getResultString(status)}>
```

Comment (AgneLukoseviciute) [inline src/examples/PermissionsExamplePage.tsx:132]:
```suggestion
        <View focusable={getResultString(status)} accessible={getResultString(status)}>
```

Comment (AgneLukoseviciute) [reply src/examples/PermissionsExamplePage.tsx:132]: I think we can simplify this, but other than that lgtm

**Review by AgneLukoseviciute — APPROVED** [review]
