### PR TITLE
Fix Theming Buggy Behavior

### LINKED ISSUE #187: Win11 dark mode, and switching RN Gallery to light mode causes some rendering issues
## Shared steps
###Repro:
1. On win 21H2, with dark mode as default
2. Launch RN Gallery app
3. Click hamburger
4. CLick settings
5. Select light theme

### Repro
6. Click hambuger
### Result
White on white menu, even no scrollbar
image

### Repro
6. Go to settings
### Result
On the settings page, notice the theme dropdown has no borders indicating it is a dropdown...
image
### Repro (cont)
7. Hover over the dropdown
### Result
Notice that now the text 'light' is white on white:
image

### Repro (cont)
8. Click on the theme dropdown
### Result
Notice that the dropdown still renders using dark theme:
image

### PR DESCRIPTION
**Pull request by chiaramooney**
### Why

Add text color adjustment with change in theme. Remove theme toggle to avoid gallery getting into unsupported state with mismatched native theme and JS theme. 

Resolves #187

### CODE REVIEW

**Review by AgneLukoseviciute — APPROVED** [review]

File: scripts/use-canary-version.js [hunk 1]
```diff
@@ -60,7 +60,7 @@ function fetchPackageInfo(pkg) {
   const manifest = JSON.parse(data);
 
   const canaryDependencies = {
-    react: peerDependencies['react'],
+    react: peerDependencies.react,
```
Comment (TatianaKapos) [inline scripts/use-canary-version.js:63]: Just curious on why it's needed to access 'react' differently than 'react-native'?

Comment (chiaramooney) [reply scripts/use-canary-version.js:63]: Unclear! This change was made automatically.
