### PR TITLE
Fix 7 accessibility bugs (Sev2)

### LINKED ISSUE #652: Fix 7 Accessibility Bugs for New Arch Gallery related to Theme
Fix below 6 bugs in gallery new arch app:
# 1. [React Native Gallery Preview]: 'All Samples" heading text is not clearly visible in 'Dark mode'
re-Requisite:
Settings > Personalization > Color > Dark.

Repro-Steps:
Launch the React Native Gallery-Preview app.
Navigate to the 'Expand menu' button and invoke it.
Navigate to ‘All samples’ button present in left navigation pane and invoke it and observe the issue.
Actual Result:
All Samples" heading text is completely not visible to the user in 'Dark mode'

Note: Same issue is observed in "High Contrast Aquatic Theme"

Expected Result:
"All samples" heading text should be clearly visible to the user in 'Dark mode'

User Impact:
Low vision or color blind users who depend on dark mode may face difficulty if the 'All Samples' heading text is not clearly visible.

# 2.[React Native Gallery Preview]: 'This text will be copied to the clipboard' edit field is not clearly visible in 'Dark mode'

Pre-Requisite:
Settings > Personalization > Color > Dark.

Repro-Steps:
Launch the React Native Gallery-Preview app.
Navigate to the 'Expand menu' button and invoke it.
Navigate to ‘All samples’ button present in left navigation pane and invoke it.
Navigate to ‘Clipboard’ button present under “System” group and invoke it.
Now observe 'This text will be copied to the clipboard' edit field present below the ‘Copy text to the Clipboard’ button
Actual Result:
'This text will be copied to the clipboard' edit field is not clearly visible in 'Dark mode'

Note: Same issue is observed for the text which is present under the 'Paste text from the Clipboard' button in both "Dark mode" & "High Contrast Aquatic Theme"

Expected Result:
'This text will be copied to the clipboard' edit field should be clearly visible to the user in 'Dark mode'

User Impact:
Low vision or color blind users who depend on dark mode may face difficulty if 'This text will be copied to the clipboard' edit field is not clearly visible in dark mode

# 3. [React Native Gallery Preview: Touchable Opacity]: 'Touchable Opacity' button present under 'A simple touchable opacity' heading is not clearly visible when High Contrast Aquatic theme is applied.

Pre-Requisite:
Open settings -> Accessibility -> Contrast themes -> Select Aquatic/Desert themes.
Repro-Steps:
Launch the React Native Gallery-Preview app.
Navigate to 'Left navigation menu' button and invoke it.
Navigate to 'All sample' list item and invoke it.
Navigate to 'Touchable opacity' item and invoke it.
Now observe the behavior of all the buttons present in this page.
Actual Result:
'Touchable Opacity' button present under 'A simple touchable opacity' heading becomes difficult or impossible to read when the High Contrast Aquatic theme is applied. 

Note: Same issue is observed for all the buttons present in 'Touchable opacity' and 'Touchable without feedback' pages.

Expected Results:
'Touchable Opacity' button present under 'A simple touchable opacity' heading should remain clearly visible to the user and readable when any high contrast theme (including Aquatic) is applied. 

User Impact:
Users with low vision who rely on high contrast themes will face difficulties to interact with the interface are unable to read or access the Settings page content.

# 4. [React Native Gallery Preview: Settings]: Content on the 'Settings' page is not clearly visible when High Contrast Aquatic theme is applied.
AT Used: High contrast

Pre-Requisite:
Open settings -> Accessibility -> Contrast themes -> Select Aquatic/Desert themes.
Repro-Steps:
Launch the React Native Gallery-Preview app.
Navigate to 'Left navigation menu' button and invoke it.
Navigate to 'Settings' button and invoke it.
Now observe the behavior of all the content present in the 'Settings' page.
Actual Result:
The content on the Settings page becomes difficult or impossible to read when the High Contrast Aquatic theme is applied. Text and background colors do not provide sufficient contrast, making the content unclear or invisible.

Expected Results:
All content on the Settings page should remain clearly visible to the user and readable when any high contrast theme (including Aquatic) is applied. 

User Impact:
Users with low vision who rely on high contrast themes will face difficulties to interact with the interface are unable to read or access the Settings page content.

# 5. [React Native Gallery Preview: Pressable]: 'Press me/Most recent event: press' buttons present in 'Pressable' page are not clearly visible when High Contrast Aquatic theme is applied.

Pre-Requisite:
Open settings -> Accessibility -> Contrast themes -> Select Aquatic/Desert themes.
Repro-Steps:
Launch the React Native Gallery-Preview app.
Navigate to 'Left navigation menu' button and invoke it.
Navigate to 'Basic input' list item and invoke it.
Navigate to 'Pressable' item and invoke it.
Now observe the behavior of all the buttons.
Actual Result:
'Press me/Most recent event: press' buttons present in 'Pressable' page becomes difficult or impossible to read when the High Contrast Aquatic theme is applied. 

Expected Results:
'Press me/Most recent event: press' buttons present in 'Pressable' page should remain clearly visible to the user and readable when any high contrast theme (including Aquatic) is applied. 

User Impact:
Users with low vision who rely on high contrast themes will face difficulties to interact with the interface are unable to read or access the button in this page.

# 6. [React Native Gallery Preview: Virtualized list]: 'Selection support: Multiple' button present under 'A virtualized list with multiple selection support' heading is not clearly visible when High Contrast Aquatic theme is applied.

Pre-Requisite:
Open settings -> Accessibility -> Contrast themes -> Select Aquatic/Desert themes.
Repro-Steps:
Launch the React Native Gallery-Preview app.
Navigate to 'Left navigation menu' button and invoke it.
Navigate to 'Collections' list item and invoke it.
Navigate to 'Virtualized list' item and invoke it.
Now observe the behavior of all the buttons present in this page.
Actual Result:
'Selection support: Multiple' button present under 'A virtualized list with multiple selection support' heading becomes difficult or impossible to read when the High Contrast Aquatic theme is applied. 

Expected Results:
'Selection support: Multiple' button present under 'A virtualized list with multiple selection support' heading should remain clearly visible to the user and readable when any high contrast theme (including Aquatic) is applied. 

User Impact:
Users with low vision who rely on high contrast themes will face difficulties to interact with the interface are unable to read or access the Settings page content.

7. [React Native Gallery Preview]: Selected list items under the 'A simple VirtualizedList' heading are not visible to the user
Build Details:
OS Version: 24H2 
OS Build: 26100.5074
App: React Native Gallery Preview

Repro-Steps:
Launch the React Native Gallery-Preview app.
Navigate to ‘All samples’ button present in left navigation pane and invoke it.
Navigate to ‘VirtualizedList’ button present under “Collection” group and invoke it.
Navigate using tab key to any item present under 'A simple VirtualizedList' heading and select it.
Now observe the selected list items 
Actual Result:
Selected list items under the 'A simple VirtualizedList' heading are not visible to the user

Expected Result:
Selected list items under the 'A simple VirtualizedList' heading should be visible clearly to the user 
Attach screenshot when done for all cases

### PR DESCRIPTION
**Pull request by anupriya13**
# Description

## Why

Resolves #652

Fixes ADO Accessibility bugs
- 59188127
- 59188404
- 59219441
- 59219340
- 59220150
- 59219526
- 59150363

## What

Fixed theme related accessibility issues

## Screenshots
| ID   | Before | After |
|----------|--------|-------|
| 59188127 | image | image |
| 59188404 | image | image |
| 59219441 | image | image |
| 59219340 | image | image |
| 59220150  | image | image |
| 59219526 | image | image |
| 59150363 | image | image |

### CODE REVIEW

File: NewArch/src/Navigation.tsx [hunk 1]
```diff
@@ -42,8 +42,36 @@ type RouteType = {
...
+    card: string;
+    text: string;
+    border: string;
+    notification: string;
+  };
+};
+
+type NavigationContainerProps = PropsWithChildren<{
+  theme?: Theme;
+}>;
```
Comment (chrisglein) [inline NewArch/src/Navigation.tsx:59]: I'm confused about the mix of a Context-style theme, and a pass through by prop theme. All while App.tsx has two other Theme contexts. Why the change to theme design here? These seems like more and I'm not sure why it doesn't blend with what's already there. Can you clarify the design?

**Review by chrisglein — CHANGES_REQUESTED** [review]

File: NewArch/package.json [hunk 2]
```diff
@@ -16,7 +16,7 @@
     "lowlight": "^1.17.0",
     "react": "19.1.0",
     "react-native": "^0.80.2",
-    "react-native-windows": "^0.80.0-preview.4"
+    "react-native-windows": "^0.80.0-preview.6"
```
[the remark this answers is not in the document]
Comment (anupriya13) [reply NewArch/package.json:19]: No but latest store has preview 6 and it's not pushed to main branch hence added here

File: NewArch/src/examples/ClipboardExamplePage.tsx [hunk 3]
```diff
@@ -65,6 +67,15 @@ export const ClipboardExamplePage: React.FunctionComponent<{navigation?: any}> =
             accessibilityLabel="Example set text to copy"
             value={textToCopy}
             onChangeText={setTextToCopy}
+            style={{
+              color: colors.text,
+              backgroundColor: colors.card,
+              borderColor: colors.border,
+              borderWidth: 1,
```
[the remark this answers is not in the document]
Comment (chrisglein) [reply NewArch/src/examples/ClipboardExamplePage.tsx:74]: Selection may have been off here. I meant the padding/margin and other sizing changes.
Also, can you clarify which image? There were a bunch but it wasn't clear which changes were for which images.

File: NewArch/src/Navigation.tsx (hunk 1 above)
Comment (chrisglein) [reply NewArch/src/Navigation.tsx:59]: But why are you creating new theme objects and types when there are already ones in src\themes and also referred to in this app's App.tsx?

Comment (chrisglein) [reply NewArch/src/Navigation.tsx:64]: Yes, thank you for tracking and documenting.
